spring.application.name=GameStore

spring.datasource.url=jdbc:postgresql://localhost:5432/GameStore
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.formal_sql=true
